/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BodyTemperature: typeof import('./src/components/BodyTemperature.vue')['default']
    ChartBodyTemperature: typeof import('./src/components/ChartBodyTemperature.vue')['default']
    ChartLineDataLabels: typeof import('./src/components/ChartLineDataLabels.vue')['default']
    ChartPolarArea: typeof import('./src/components/ChartPolarArea.vue')['default']
    DataTableBodyTemperature: typeof import('./src/components/DataTableBodyTemperature.vue')['default']
    ReloadPWA: typeof import('./src/components/ReloadPWA.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teste: typeof import('./src/components/teste.vue')['default']
  }
}
